name: Dockerize
on: push
jobs:
  setup: 
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

  deployMain:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: setup
    steps:
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ttl.sh/hellofastapi20230823:24h

  deployBranch:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    needs: setup
    steps:
      - name: Print the branch name
        run: echo The branch name is ${GITHUB_REF##*/}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ttl.sh/hellofastapi20230823-${GITHUB_REF##*/}:24h   
